spring.application.name=auth-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5440/authdbdashy
spring.datasource.username=authdbdashy
spring.datasource.password=authdbdashy
spring.jpa.hibernate.ddl-auto=update

# Log to both file and console
logging.file.name=application.log
logging.file.path=logs
logging.level.root=INFO

# Basic mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amine.eco.store@gmail.com
spring.mail.password=yaij abls keyc yruy
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
